# Generated by Django 4.1.4 on 2022-12-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d'),
        ),
    ]
