# Generated by Django 4.1.4 on 2022-12-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_employee_options_employee_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gener',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
