# Generated by Django 4.1.4 on 2022-12-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_gener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gener',
        ),
    ]
